apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bjol09hex-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bjol09hex-go 
  name: bjol09hex-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bjol09hex-go 
